services:
  - type: web
    name: telegram-bot
    runtime: python
    env: python
    region: oregon  # можно оставить по умолчанию

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"

    envVars:
      - key: BOT_TOKEN
        sync: false
        fromFile: false
